server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
    username: root
    password: asdf1234
    platform: mysql
  jpa:
    hibernate:
      # 이미 테이블이 존재하는 상황에서 @Entity 의 속성이 추가될경우,
      # 기존의 테이블의 데이터에는 변화없이 새로운 컬럼을 추가해준다.
#      ddl-auto: update

    # JPA 나 hibernate 를 통해 CRUD 를 실행하면 해당 CRUD 의 sql 을 로깅으로 보여준다.
    show-sql: true